volumes:
  postgres:

services:
  main_db:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_JDBC_URL: 'jdbc:postgresql://main_db:5432/postgres'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    depends_on:
      - main_db